# Generated by Django 4.2.1 on 2023-05-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_by", models.DateField(auto_now_add=True)),
                ("updated_by", models.DateField(auto_now=True)),
                ("departmentId", models.AutoField(primary_key=True, serialize=False)),
                ("departmentName", models.CharField(max_length=30)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_by", models.DateField(auto_now_add=True)),
                ("updated_by", models.DateField(auto_now=True)),
                ("EmployeeId", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeeName", models.CharField(max_length=30)),
                ("DateOfJoin", models.DateField()),
                ("EmployeeProfile", models.ImageField(null=True, upload_to="")),
                (
                    "Department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmployeeApp.department",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
