# Generated by Django 4.2.1 on 2023-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0002_alter_employee_employeeprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="EmployeeProfile",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
